### ISSUE TITLE
Update JSDOM for Unit Testing/or consider Jekyll

### ISSUE THREAD

**Issue by poorejc** [apache/incubator-flagon-useralejs#14]
Unit testing framework is a little dated, though wholly sufficient. Should at minimum upgrade to JSDOM 10, or consider refactoring in Jekyll.

**Comment by UncleGedd** [comment]
See [pull request](https://github.com/apache/incubator-flagon-useralejs/pull/40)

**Comment by poorejc** [comment]
Thanks @UncleGedd for helping with this!
