### ISSUE TITLE
Address new package vulnerabilities

### ISSUE THREAD

**Issue by poorejc** [apache/incubator-flagon-useralejs#196]
Update devdependencies in package.js to remove package vulnerabilities in build pipeline

**Comment by UncleGedd** [comment]
Hey Josh! Happy to do these updates, will have a PR ready soon

**Comment by poorejc** [comment]
@UncleGedd you don't want to lead the release packaging?? :)

Thanks Gedd. This is the forever work. I pushed a major update to dev dependencies last weekend, and we're already backlogged in new bot PRs. I'll test and review your PR tonight! Cheers!

**Comment by UncleGedd** [comment]
Ha! Consider this my +1 VOTE

**Comment by UncleGedd** [comment]
Closed with: https://github.com/apache/incubator-flagon-useralejs/pull/202
