### ISSUE TITLE
WebExt: Add alternative Fetch 'SendLogs' function to support changes to webextensions

### ISSUE THREAD

**Issue by poorejc** [apache/incubator-flagon-useralejs#285]
Chrome MV3 has moved to service workers, abandoning the historical "Background Pages". As such this will not support XMLhttpRequest, favoring Fetch.

UserALE's SendLogs function uses XMLhttpRequest. As such, we'll need to the WebExt to use it's own SendLogs function using Fetch.

https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#background-service-workers

Mozilla is adopting MV3 in full to support cross-browser compatability

**Comment by brucearctor** [comment]
@poorejc -- per:  https://github.com/apache/incubator-flagon-useralejs/pull/286 this issue can be closed, is that right?

**Comment by poorejc** [comment]
Correct, this is closed, although the MV3 madness is far from done with us.
