### ISSUE TITLE
Event.path is deprecated

### ISSUE THREAD

**Issue by Jyyjy** [apache/incubator-flagon-useralejs#311]
While testing the web extension today, I got the following warning from chrome:

"Event.path is deprecated and will be removed. Please use Event.composedPath() instead"

Here is the status of the removal of event.path:
https://chromestatus.com/feature/5726124632965120

It is scheduled to go into effect at milestone 109 in January 2023:
https://chromiumdash.appspot.com/schedule

We should update to composedPath(), which actually looks like it will simplify some of the code in packageLogs.js

**Comment by poorejc** [comment]
NICE catch. This is a priority! Lets work together on this!

**Comment by poorejc** [comment]
Closed with PR #323
