### ISSUE TITLE
How to deploy in a a load balancing environment?

### ISSUE THREAD

**Issue by yogeshkodei** [apache/incubator-flagon-useralejs#51]
We have a proxy server that redirects user requests to different servers for load balancing. On the proxy side we have our UI application. Some analytics do need to track information about the host. That being said what is the advice wrt:
1. Capturing every user interaction with the application would eventually end up creating large volume of data relatively quickly. Is there a way to purge data that is “x” days old or some retention/deletion policy of some sort?
2. Is there a need to have a cluster of ELK or is one sufficient?

**Comment by poorejc** [comment]
let's move this discussion over the incubator-flagon project (this is where we keep all the ELK resources). Gonna coppy this ticket over to: https://github.com/apache/incubator-flagon/issues/20
