### ISSUE TITLE
add LogType = Raw and Type = load to PageLoad Custom Log

### ISSUE THREAD

**Issue by poorejc** [apache/incubator-flagon-useralejs#58]
minor mods to make this easier to index and search in back end solution (e.g., ELK)

**Comment by poorejc** [comment]
Minor mod keeps schema consistent for back end indexing.
  
{
    pageUrl: 'file://...Apache_Flagon/test/incubator-flagon-useralejs/example/index.html?',
    pageTitle: 'UserALE.js - Example Page',
    pageReferrer: '',
    browser: { browser: 'chrome', version: '89.0.4389' },
    clientTime: 1615606924803,
    scrnRes: { width: 1080, height: 666 },
    **logType: 'raw',**
    userAction: false,
    userId: 'me',
    toolVersion: '2.1.1',
    toolName: 'Apache UserALE.js Example (Custom)',
    useraleVersion: '2.1.1',
    sessionID: 'session_1615606602389',
    **type: 'load',**
    pageLoadTime: 5
  },

**Comment by poorejc** [comment]
reopening for deeper integration testing

**Comment by UncleGedd** [comment]
This could be a good opportunity to bring in Cypress and assert on the payloads being sent to the backend. If you like that idea I'll start work on a PR

**Comment by poorejc** [comment]
That's a good idea. Just note that I have some commits to address this issue up on the test branch. Pull from test check out the fields I added on your pageLoad code in src/main.js. Then feel free to play around with cypress. I'm brand new to cypress, so I'm catching up to you!

**Comment by poorejc** [comment]
tested and pushed with https://github.com/apache/incubator-flagon-useralejs/commit/7a7b2ce73963d9dd1b0bff9419ded12e15af10ad
